{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "8a34e07e",
   "metadata": {},
   "outputs": [],
   "source": [
    "import json, requests"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "id": "8bb4ba1f",
   "metadata": {},
   "outputs": [],
   "source": [
    "'''Login: Obtener accessToken'''\n",
    "\n",
    "XClientId = 'c0c8cf02-e18b-4d9e-9af6-23ce93374c93'\n",
    "passKey = '0676E16E4BE099A19D550C790D54CF9C4868156FEF13AA1389DA18A3DA5A85E7DD21632FCB75DF85AA623919697E4FBF823538E71B4105671A02865167901077'\n",
    "response1 = requests.get('https://openapi.emtmadrid.es/v1/mobilitylabs/user/login/', headers={'X-ClientId': XClientId, 'passKey': passKey})\n",
    "text = response1.text\n",
    "data1 = json.loads(text)\n",
    "accessToken = data1['data'][0]['accessToken']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "id": "371355fe",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>name</th>\n",
       "      <th>light</th>\n",
       "      <th>number</th>\n",
       "      <th>address</th>\n",
       "      <th>activate</th>\n",
       "      <th>no_available</th>\n",
       "      <th>total_bases</th>\n",
       "      <th>dock_bikes</th>\n",
       "      <th>free_bases</th>\n",
       "      <th>reservations_count</th>\n",
       "      <th>geometry</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>1a - Puerta del Sol A</td>\n",
       "      <td>0</td>\n",
       "      <td>1a</td>\n",
       "      <td>Puerta del Sol nº 1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>30</td>\n",
       "      <td>7</td>\n",
       "      <td>21</td>\n",
       "      <td>0</td>\n",
       "      <td>{'type': 'Point', 'coordinates': [-3.7018341, ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>1b - Puerta del Sol B</td>\n",
       "      <td>2</td>\n",
       "      <td>1b</td>\n",
       "      <td>Puerta del Sol nº 1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>30</td>\n",
       "      <td>13</td>\n",
       "      <td>16</td>\n",
       "      <td>0</td>\n",
       "      <td>{'type': 'Point', 'coordinates': [-3.701602938...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>2 - Miguel Moya</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>Calle Miguel Moya nº 1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>24</td>\n",
       "      <td>11</td>\n",
       "      <td>12</td>\n",
       "      <td>0</td>\n",
       "      <td>{'type': 'Point', 'coordinates': [-3.7058415, ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>3 - Plaza Conde Suchil</td>\n",
       "      <td>2</td>\n",
       "      <td>3</td>\n",
       "      <td>Plaza del Conde del Valle de Súchil nº 3</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>18</td>\n",
       "      <td>8</td>\n",
       "      <td>10</td>\n",
       "      <td>0</td>\n",
       "      <td>{'type': 'Point', 'coordinates': [-3.7069171, ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>4 - Malasaña</td>\n",
       "      <td>0</td>\n",
       "      <td>4</td>\n",
       "      <td>Calle Manuela Malasaña nº 5</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>24</td>\n",
       "      <td>3</td>\n",
       "      <td>19</td>\n",
       "      <td>0</td>\n",
       "      <td>{'type': 'Point', 'coordinates': [-3.7025875, ...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   id                    name  light number  \\\n",
       "0   1   1a - Puerta del Sol A      0     1a   \n",
       "1   2   1b - Puerta del Sol B      2     1b   \n",
       "2   3         2 - Miguel Moya      2      2   \n",
       "3   4  3 - Plaza Conde Suchil      2      3   \n",
       "4   5            4 - Malasaña      0      4   \n",
       "\n",
       "                                    address  activate  no_available  \\\n",
       "0                       Puerta del Sol nº 1         1             0   \n",
       "1                       Puerta del Sol nº 1         1             0   \n",
       "2                    Calle Miguel Moya nº 1         1             0   \n",
       "3  Plaza del Conde del Valle de Súchil nº 3         1             0   \n",
       "4               Calle Manuela Malasaña nº 5         1             0   \n",
       "\n",
       "   total_bases  dock_bikes  free_bases  reservations_count  \\\n",
       "0           30           7          21                   0   \n",
       "1           30          13          16                   0   \n",
       "2           24          11          12                   0   \n",
       "3           18           8          10                   0   \n",
       "4           24           3          19                   0   \n",
       "\n",
       "                                            geometry  \n",
       "0  {'type': 'Point', 'coordinates': [-3.7018341, ...  \n",
       "1  {'type': 'Point', 'coordinates': [-3.701602938...  \n",
       "2  {'type': 'Point', 'coordinates': [-3.7058415, ...  \n",
       "3  {'type': 'Point', 'coordinates': [-3.7069171, ...  \n",
       "4  {'type': 'Point', 'coordinates': [-3.7025875, ...  "
      ]
     },
     "execution_count": 47,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "response2 = requests.get('https://openapi.emtmadrid.es/v1/transport/bicimad/stations/', headers={'accessToken': accessToken})\n",
    "text = response2.text\n",
    "data2 = json.loads(text)['data']\n",
    "data2 = pd.DataFrame(data2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "be3d8279",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.12"
  },
  "toc": {
   "base_numbering": 1,
   "nav_menu": {},
   "number_sections": true,
   "sideBar": true,
   "skip_h1_title": false,
   "title_cell": "Table of Contents",
   "title_sidebar": "Contents",
   "toc_cell": false,
   "toc_position": {},
   "toc_section_display": true,
   "toc_window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
